AllCops:
  TargetRubyVersion: 2.4
  DisabledByDefault: true

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Layout:
  Enabled: true

Performance:
  Enabled: true

Security:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/RedundantFreeze:
  Enabled: true
