dist: xenial
language: ruby
cache: bundler
rvm:
  - ruby-head
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - 2.3.8
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

before_install:
  - wget http://archive.ubuntu.com/ubuntu/pool/universe/f/faketime/libfaketime_0.9.7-3_amd64.deb
  - sudo dpkg -i libfaketime_0.9.7-3_amd64.deb
  - gem install bundler -v "~> 2.0"

before_script:
  - export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1
  - export DONT_FAKE_MONOTONIC=1
  - export FAKETIME_NO_CACHE=1
