dist: xenial
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.0-preview3
  - 2.5.3
  - 2.4.5
  - 2.3.8
matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.6.0-preview3

before_install:
  - gem install bundler -v "~> 1.17"
